### ISSUE TITLE
Add preparation for caching

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/SpringbootGroupProject#21]
Add preparation for caching of the most used SQL-commands to lower user impact on our application.

Add:
- `<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>` to pom.xml
- `@EnableCaching` to JpaConfiguration

To enable caching, the objects we want to be able to cache needs `implements Serializable`
The question we want caching for needs `@Cacheable("insertName")`
To clear the cache when ex. Adding new object to repo we need `@CacheEvict(value = "inserName", allEntries = true)` on the method that needs to invalidate the current caching.

What do you think, do we want to implement caching in our application or is this unnecesary for the size of our application? Is this something we should do later on when we have a functioning application or is preparing for it better as to implement during development?

**Comment by marcusju23** [comment]
I'm fully onboard with this. Implementing caching not only enhances our application's performance but also makes us grow as developers and might benefit us in future projects. Let's seize this opportunity to expand our skills and knowledge! 😄

**Comment by Frlundsten** [comment]
> I'm fully onboard with this. Implementing caching not only enhances our application's performance but also makes us grow as developers and might benefit us in future projects. Let's seize this opportunity to expand our skills and knowledge! 😄

Agreed, we should implement it to learn more on how to use cache and how we could apply it to our own application. Great issue 👍
