### ISSUE TITLE
Add Validators

### ISSUE THREAD

**Issue by marcusju23** [Win-ther/SpringbootGroupProject#51]
The system should feature validators for diverse data inputs, ensuring integrity by preventing invalid entries. It should cover strings, numbers, dates, and custom formats, offering customizable error messages for user guidance.

**Additional context**
[Implementing Validations for RESTful Services](https://www.javatpoint.com/restful-web-services-validations)
[Spring docs - Validation](https://docs.spring.io/spring-framework/reference/web/webflux/controller/ann-validation.html)

**Comment by Win-ther** [comment]
Can this Issue be closed? Since we have validators for relevant DTO-classes where the user can enter information. Or is there more to add that I am missing?

**Comment by marcusju23** [comment]
Yes, let's close this issue.
