### ISSUE TITLE
Implement Lombok

### ISSUE THREAD

**Issue by Frlundsten** [Win-ther/SpringbootGroupProject#55]
**Clean code**
We should use Lombok annotations to keep our code clean. 

When using the Lombok annotations we can omit large parts of the boilerplate Java code like, getters , setters and constructors. As an example we can go from a block of code like ->

```
public class User {
    private long id;
    private String login;
    private int age;

    public long getId() {
        return this.id;
    }

    public String getLogin() {
        return this.login;
    }

    public int getAge() {
        return this.age;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setLogin(String login) {
        this.login = login;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
```

to 

```
@Setter
@Getter
public class User {
    private long id;
    private String login;
    private int age;
}

**Comment by marcusju23** [comment]
Some considerations to keep in mind are the potential for limited tool support, the possibility of encountering debugging complexities, and compatibility concerns. Additionally, excessive use of Lombok could obscure the clarity of the codebase. So while Lombok does help get things done faster, it's important to use it wisely and think about its effects, from my understanding 🤔

I haven't used Lombok before, but it seems like it could be a good addition to try out for our project 👍

[Lombok • The Good, The Bad, and The Ugly](https://www.kapresoft.com/java/2023/11/07/lombok-good-bad-ugly.html)

**Comment by Frlundsten** [comment]
> Some considerations to keep in mind are the potential for limited tool support, the possibility of encountering debugging complexities, and compatibility concerns. Additionally, excessive use of Lombok could obscure the clarity of the codebase. So while Lombok does help get things done faster, it's important to use it wisely and think about its effects, from my understanding 🤔
> 
> I haven't used Lombok before, but it seems like it could be a good addition to try out for our project 👍
> 
> [Lombok • The Good, The Bad, and The Ugly](https://www.kapresoft.com/java/2023/11/07/lombok-good-bad-ugly.html)

Yes there are alot of pros and cons but since its a widely used library in projects and since the assignment brings it up as dependency (according to Martin Lombok is not critical for the project though!) I think that we probably should implement it so that we can get a feel for how it works.
![image](https://github.com/Win-ther/SpringbootGroupProject/assets/130497295/40384b65-5c9e-444f-becc-6c5825c89394)

More on lombok [here](https://projectlombok.org/features/GetterSetter)
