### ISSUE TITLE
Add testing?

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/SpringbootGroupProject#64]
As our project is right now we do not have a single test.

Should we maybe add some testing?
Unit-tests
Integration-tests
Martin wen't through this some in the lectures, does anyone know which one?

**Comment by altmannk** [comment]
[Spring Boot - Security-20240326_130013-Mötesinspelning](https://ithogskolan.sharepoint.com/:v:/s/Java23/EUxLSw9sxVxNs-ODclJwCm4BuvgeqraFLuEDFVFvGK7JJQ?e=fkgypR&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifSwicGxheWJhY2tPcHRpb25zIjp7InN0YXJ0VGltZUluU2Vjb25kcyI6NTI4MS42N319)

**Comment by marcusju23** [comment]
Yes let's add some testing! 👍 I'm going to make separate issues for each package so we don't work on the same tests.

**Comment by Win-ther** [comment]
Closing this as we have separate issues for testing.
