### ISSUE TITLE
Add message-filter

### ISSUE THREAD

**Issue by Frlundsten** [Win-ther/SpringbootGroupProject#75]
**Meddelanden kan visas baserat på vem som har publicerat dem.**

**Additional context**
Wee need a way  ( maby in /message or /welcome ) so that we can filter the shown messages based on who wrote them.

**Comment by Win-ther** [comment]
We technically have a way to show messages based on who published them by going to /myprofile 😉 But it's probably better to add some kind of search-button that takes you to a form in which you can enter a username that then directs you to a version of messages with a pathparam or queryparam. It should probably be made from /message
![image](https://github.com/Win-ther/SpringbootGroupProject/assets/143023413/0396e747-d322-4fb5-a87b-5536303a66f8)

**Comment by Frlundsten** [comment]
> We technically have a way to show messages based on who published them by going to /myprofile 😉 But it's probably better to add some kind of search-button that takes you to a form in which you can enter a username that then directs you to a version of messages with a pathparam or queryparam. It should probably be made from /message ![image](https://private-user-images.githubusercontent.com/143023413/320078126-0396e747-d322-4fb5-a87b-5536303a66f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzYxMDQsIm5iZiI6MTcxMjMzNTgwNCwicGF0aCI6Ii8xNDMwMjM0MTMvMzIwMDc4MTI2LTAzOTZlNzQ3LWQzMjItNGZiNS1hODdiLTU1MzYzMDNhNjZmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxNjUwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZmMyMTI0ZmQzNjMyNzNjNmQwZDdkMjYxZmY2YzE1NzJlNDcyMzI4OTYyZjA2OTc2ZTBjZjk0NGU4M2M1NjBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IatfoXg1R-be4rRiHmZYaXxjWfPD0Hl7MYFMbRnLKn0)

I agree! I can grab this issue after i fix controller tests. 
And I am 100% going to use that paint "SEARCH" as a button for the function 😆
