### ISSUE TITLE
Standard for Entities and DTOs with Lombok.

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/SpringbootGroupProject#78]
As it is right now we have mixed using Lombok and not using Lombok in Entities/DTOs. We should refactor our code to either actually use Lombok annotations, or remove it from our project and just use normal Getter/Setter/Constructor methods.
What do you think?

**Comment by marcusju23** [comment]
I'm glad you brought it up. Since Lombok is already integrated into our project, a refactor would be great to enhance uniformity throughout our project. We might need to correct some tests but that should be fine 👍

**Comment by Win-ther** [comment]
> I'm glad you brought it up. Since Lombok is already integrated into our project, a refactor would be great to enhance uniformity throughout our project. We might need to correct some tests but that should be fine 👍

Yes we should probably wait for the tests for entities and dtos to be merged before doing this.

**Comment by Frlundsten** [comment]
Yes a refactor would be nice! What kind of tests will have to be corrected?
