### ISSUE TITLE
Add OAuth2-login

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/SpringbootGroupProject#8]
### Authentication
- Setup OAuth2 so that users can authenticate through GitHub to get access to our application.
- Add spring-boot-starter-security and spring-boot-starter-oauth2-client dependencies
- Add application.properties for GitHub Oauth2 client id and secret

**Comment by marcusju23** [comment]
```
<dependency>
    <groupId>org.springframework.retry</groupId>
    <artifactId>spring-retry</artifactId>
    <version>2.0.5</version>
</dependency>
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-aspects</artifactId>
    <version>6.1.5</version>
</dependency>
```
https://www.baeldung.com/spring-retry
