### ISSUE TITLE
Translation of messages using external api

### ISSUE THREAD

**Issue by Win-ther** [Win-ther/SpringbootGroupProject#9]
https://github.com/LibreTranslate/LibreTranslate

**Comment by altmannk** [comment]
https://github.com/dynomake/libretranslate-java

**Comment by altmannk** [comment]
<img width="786" alt="image" src="https://github.com/Win-ther/SpringbootGroupProject/assets/143100902/b866011e-065b-434e-a0fa-3f2d872c2a07">

**Comment by altmannk** [comment]
<img width="786" alt="image" src="https://github.com/Win-ther/SpringbootGroupProject/assets/143100902/f01b6380-ef62-468f-ac10-4092da46bac7">

**Comment by altmannk** [comment]
I'll give this a try. Have a little mercy pls😂

**Comment by marcusju23** [comment]
I think adding this to `compose.yaml` should do it.

![image](https://github.com/Win-ther/SpringbootGroupProject/assets/143085217/56c568c9-cab9-4a1f-b779-66da78fda9c4)
